behaviors:
  DroneGrid3D:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: False
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: False
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: False
      # MEMORY CONFIGURATION
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # CURIOSITY LEARNING
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
        learning_rate: 0.0003
    keep_checkpoints: 25
    checkpoint_interval: 100000
    max_steps: 2500000
    time_horizon: 256
    summary_freq: 50000
# CURRICULUM CONFIGURATION
environment_parameters:
  #RANDOM OBSTACLE GENERATION ("WHITE NOISE")
  map_type: 1.0
  grid_size: 20.0

  density:
    curriculum:
      - name: Empty refresher
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0.0
      - name: LightObstacles
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 400
          threshold: 0.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.05
            max_value: 0.1
      - name: MediumObstacles
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 600
          threshold: 0.75
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.1
            max_value: 0.15
      - name: HeavyObstacles
        # completion_criteria:
        #   measure: reward
        #   behavior: DroneGrid3D
        #   signal_smoothing: true
        #   min_lesson_length: 800
        #   threshold: 0.7
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.15
            max_value: 0.2
      # - name: DenseObstacles
      #   completion_criteria:
      #     measure: reward
      #     behavior: DroneGrid3D
      #     signal_smoothing: true
      #     min_lesson_length: 1000
      #     threshold: 0.7
      #   value:
      #     sampler_type: uniform
      #     sampler_parameters:
      #       min_value: 0.2
      #       max_value: 0.3
      # - name: ThresholdObstacles
      #   completion_criteria:
      #     measure: reward
      #     behavior: DroneGrid3D
      #     signal_smoothing: true
      #     min_lesson_length: 1200
      #     threshold: 0.7
      #   value:
      #     sampler_type: uniform
      #     sampler_parameters:
      #       min_value: 0.3
      #       max_value: 0.4
      # - name: MaximumObstacles
      #   value: 0.5
