behaviors:
  DroneGrid3D:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: False
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: False
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: False
      # MEMORY CONFIGURATION
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # CURIOSITY LEARNING
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
        learning_rate: 0.0003
    keep_checkpoints: 25
    checkpoint_interval: 100000
    max_steps: 2500000
    time_horizon: 256
    summary_freq: 50000
# CURRICULUM CONFIGURATION
environment_parameters:
  #RANDOM OBSTACLE GENERATION ("WHITE NOISE")
  map_type: 0.0
  density: 0.0

  grid_size:
    curriculum:
      - name: VerySmallRoom
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.8
        value: 5.0
      - name: SmallRoom
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 10.0
      - name: MediumRoom
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 15.0
      - name: LargeRoom
        completion_criteria:
          measure: reward
          behavior: DroneGrid3D
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 20.0
      - name: FinalRoom
        value: 32.0
  # density:
  #   curriculum:
  #     - name: NoDensity
  #       completion_criteria:
  #         measure: reward
  #         behavior: DroneGrid3D
  #         signal_smoothing: true
  #         min_lesson_length: 200
  #         threshold: 0.8
  #       value: 0.0
  #     - name: SmallDensity
  #       completion_criteria:
  #         measure: reward
  #         behavior: DroneGrid2D
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 0.7
  #       value:
  #         sampler_type: uniform
  #         sampler_parameters:
  #           min_value: 0.1
  #           max_value: 0.3
  #     - name: AverageDensity
  #       completion_criteria:
  #         measure: reward
  #         behavior: DroneGrid2D
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 0.8
  #       value:
  #         sampler_type: uniform
  #         sampler_parameters:
  #           min_value: 0.3
  #           max_value: 0.5
  #     - name: BigDensity
  #       completion_criteria:
  #         measure: reward
  #         behavior: DroneGrid2D
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 0.8
  #       value:
  #         sampler_type: uniform
  #         sampler_parameters:
  #           min_value: 0.5
  #           max_value: 0.6
  #     - name:
  #       completion_criteria:
  #         measure: reward
  #         behavior: DroneGrid2D
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 0.8
  #       value:
  #         sampler_type: uniform
  #         sampler_parameters:
  #           min_value: 0.6
  #           max_value: 0.8
  #     - name: MaximumDensity
  #       value: 0.8
